spring:
  application:
    name: restaurant-service

  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true